###
GET http://localhost:8080/imageData/{{uuid}}





###
POST http://localhost:8080/image
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: imageData/jpeg

@./example.jpg

--Boundary
Content-Disposition: form-data; name="imageBody"
Content-Type: application/json

{
  "name": "example-imageData",
  "fileName": "example.jpg",
  "fileLocation": "/path/to/example.jpg",
  "metadata": {
    "key1": "value1",
    "key2": "value2",
    "key3": "value3"
  }
}

--Boundary



###
POST http://localhost:8080/image
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="file"; filename="20220424_194625.jpg"
Content-Type: image/jpeg

< /Users/handongheon/Documents/20220424_194625.jpg
--BOUNDARY
Content-Disposition: form-data; name="imageBody"
Content-Type: application/json

{
"imageBody": {
  "name": "example-imageData",
  "fileName": "example.jpg"
  }
}
