amazon:
  sqs:
    workflow:
      URL: "https://sqs.ap-northeast-2.amazonaws.com/417762818207/WorkflowQueue.fifo"
      name:  "WorkflowQueue.fifo"

--- # localhost

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/imageTagManagementDatabase"
    username: "appuser"
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: local

upload:
  directory : "/Users/handongheon/project/uploadRepository"



logging:
  level:
    com.intelligent.imagetagmanagement: DEBUG


--- # develop

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/imageTagManagementDatabase"
    username: "appuser"
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev

upload:
  directory : "/Users/handongheon/project/uploadRepository"

logging:
  level:
    com.intelligent.imagetagmanagement: DEBUG

