
--- # localhost

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/imageTagManagementDatabase"
    username: "appuser"
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: local

upload:
  directory : "/Users/handongheon/project/uploadRepository"

logging:
  level:
    com.intelligent.imageTagManagement : DEBUG


--- # develop

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/imageTagManagementDatabase"
    username: "appuser"
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev

upload:
  directory : "/Users/handongheon/project/uploadRepository"

logging:
  level:
    com.intelligent.imageTagManagement : DEBUG

